version: '3.5'

services:
  postgres:
    container_name: postgres_nestjs_paginate
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    ports:
      - "5432:5432"
